Resources:
  resourceLambdaPolicy:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: lambda.amazonaws.com}
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: 
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: ['s3:*', 'ec2:DescribeSnapshots']
            Resource: ['*']
          - Effect: Allow
            Action: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents']
            Resource: arn:aws:logs:*:*:*
  resourceDeleteSnapshotsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: {'Fn::ImportFile': delete-old-snapshots.min.js}
      Description: 'Deletes snapshots older than a month that have a specific tag key/value'
      Handler: 'index.handler'
      MemorySize: 128
      Runtime: nodejs4.3
      Timeout: 300
      Role: {'Fn::GetAtt': [ resourceDeleteSnapshotsRole, Arn ]}
